<script setup lang="ts">
import { computed } from 'vue'
import type { Component } from 'vue'
import {
  AcademicCapIcon,
  ArrowLeftIcon,
  ArrowPathIcon,
  ArrowRightIcon,
  ArrowRightOnRectangleIcon,
  Bars3Icon,
  BellIcon,
  BoltIcon,
  BriefcaseIcon,
  BuildingOfficeIcon,
  CalendarIcon,
  ChatBubbleBottomCenterTextIcon,
  CheckBadgeIcon,
  CheckCircleIcon,
  CheckIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  CircleStackIcon,
  ClipboardDocumentCheckIcon,
  ClipboardDocumentIcon,
  ClipboardDocumentListIcon,
  ClipboardIcon,
  ClockIcon,
  CloudArrowUpIcon,
  CodeBracketIcon,
  Cog6ToothIcon,
  DocumentIcon,
  DocumentTextIcon,
  EllipsisHorizontalIcon,
  ExclamationCircleIcon,
  ExclamationTriangleIcon,
  FolderIcon,
  FolderOpenIcon,
  GlobeAltIcon,
  HomeIcon,
  IdentificationIcon,
  InboxIcon,
  LightBulbIcon,
  LinkIcon,
  LockClosedIcon,
  MagnifyingGlassIcon,
  MegaphoneIcon,
  PaperAirplaneIcon,
  PaperClipIcon,
  PencilSquareIcon,
  PhotoIcon,
  PlusIcon,
  PresentationChartLineIcon,
  QuestionMarkCircleIcon,
  RectangleStackIcon,
  RocketLaunchIcon,
  ShareIcon,
  ShieldCheckIcon,
  SparklesIcon,
  Square3Stack3DIcon,
  StarIcon,
  StopCircleIcon,
  TrashIcon,
  UserCircleIcon,
  UserGroupIcon,
  UserIcon,
  UserPlusIcon,
  UsersIcon,
  VideoCameraIcon,
  ViewColumnsIcon,
  XCircleIcon,
  XMarkIcon,
} from '@heroicons/vue/24/outline'

const props = defineProps<{
  name?: string
}>()

const icons: Record<string, Component> = {
  'academic-cap': AcademicCapIcon,
  'arrow-left': ArrowLeftIcon,
  'arrow-path': ArrowPathIcon,
  'arrow-right': ArrowRightIcon,
  'arrow-right-on-rectangle': ArrowRightOnRectangleIcon,
  'bars-3': Bars3Icon,
  bell: BellIcon,
  bolt: BoltIcon,
  briefcase: BriefcaseIcon,
  'building-office': BuildingOfficeIcon,
  calendar: CalendarIcon,
  'chat-bubble-left-text': ChatBubbleBottomCenterTextIcon,
  check: CheckIcon,
  'check-badge': CheckBadgeIcon,
  'check-circle': CheckCircleIcon,
  'chevron-left': ChevronLeftIcon,
  'chevron-right': ChevronRightIcon,
  circle: StopCircleIcon,
  'circle-stack': CircleStackIcon,
  clipboard: ClipboardIcon,
  'clipboard-document': ClipboardDocumentIcon,
  'clipboard-document-check': ClipboardDocumentCheckIcon,
  'clipboard-document-list': ClipboardDocumentListIcon,
  clock: ClockIcon,
  'cloud-arrow-up': CloudArrowUpIcon,
  'code-bracket': CodeBracketIcon,
  'cog-6-tooth': Cog6ToothIcon,
  crown: StarIcon,
  document: DocumentIcon,
  'document-text': DocumentTextIcon,
  'ellipsis-horizontal': EllipsisHorizontalIcon,
  'exclamation-circle': ExclamationCircleIcon,
  'exclamation-triangle': ExclamationTriangleIcon,
  folder: FolderIcon,
  'folder-open': FolderOpenIcon,
  'globe-alt': GlobeAltIcon,
  home: HomeIcon,
  identification: IdentificationIcon,
  inbox: InboxIcon,
  layers: RectangleStackIcon,
  'light-bulb': LightBulbIcon,
  link: LinkIcon,
  'lock-closed': LockClosedIcon,
  'magnifying-glass': MagnifyingGlassIcon,
  megaphone: MegaphoneIcon,
  'paper-airplane': PaperAirplaneIcon,
  'paper-clip': PaperClipIcon,
  'pencil-square': PencilSquareIcon,
  photo: PhotoIcon,
  plus: PlusIcon,
  'presentation-chart-line': PresentationChartLineIcon,
  'rocket-launch': RocketLaunchIcon,
  share: ShareIcon,
  'shield-check': ShieldCheckIcon,
  sparkles: SparklesIcon,
  'square-3-stack-3d': Square3Stack3DIcon,
  star: StarIcon,
  trash: TrashIcon,
  user: UserIcon,
  'user-circle': UserCircleIcon,
  'user-group': UserGroupIcon,
  'user-plus': UserPlusIcon,
  users: UsersIcon,
  'video-camera': VideoCameraIcon,
  'view-columns': ViewColumnsIcon,
  'x-circle': XCircleIcon,
  'x-mark': XMarkIcon,
}

const icon = computed(() => {
  if (!props.name?.startsWith('i-heroicons-')) {
    return QuestionMarkCircleIcon
  }

  return icons[props.name.replace(/^i-heroicons-/, '')] || QuestionMarkCircleIcon
})
</script>

<template>
  <component :is="icon" aria-hidden="true" />
</template>
